

name: Network Getting Started First Playbook
  connection: 127.0.0.1
  gather_facts: false
  hosts: all
  tasks:

    name: Get config for VyOS devices
      vyos.vyos.vyos_facts:
        gather_subset: all

    name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
