# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: no
      addresses: [172.18.68.4/24]
      gateway4: 172.18.68.1
      nameservers:
         addresses: [8.8.8.8,8.8.4.4]
  version: 2
